src/Entity/Livraison.php
<?php

namespace App\Entity;

use App\Repository\LivraisonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LivraisonRepository::class)]
class Livraison
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("livraison")]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Product Name required")]
    #[Groups("livraison")]
    private ?string $name_produit = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Artiste required")]
    #[Groups("livraison")]
    private ?string $artiste = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"addres required")]
    #[Groups("livraison")]
    private ?string $addres = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\LessThanOrEqual('today',message:"We Do NOT LIVE IN THE FUTURE")]
    #[Groups("livraison")]

    private ?\DateTimeInterface $date_sort = null;

    #[ORM\OneToOne()]
    #[Assert\NotNull(message:"Please select one")]
    #[Groups("livraison")]
    private ?Commande $id_commende = null;



    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"User Name required")]
    #[Groups("livraison")]
    private ?string $user_name = null;







    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameProduit(): ?string
    {
        return $this->name_produit;
    }

    public function setNameProduit(string $name_produit): self
    {
        $this->name_produit = $name_produit;

        return $this;
    }

    public function getArtiste(): ?string
    {
        return $this->artiste;
    }

    public function setArtiste(string $artiste): self
    {
        $this->artiste = $artiste;

        return $this;
    }

    public function getAddres(): ?string
    {
        return $this->addres;
    }

    public function setAddres(string $addres): self
    {
        $this->addres = $addres;

        return $this;
    }

    public function getDateSort(): ?\DateTimeInterface
    {
        return $this->date_sort;
    }

    public function setDateSort(\DateTimeInterface $date_sort): self
    {
        $this->date_sort = $date_sort;

        return $this;
    }

    public function getIdCommende(): ?commande
    {
        return $this->id_commende;
    }

    public function setIdCommende(?commande $id_commende): self
    {
        $this->id_commende = $id_commende;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }



}

src/Form/LivraisonType.php
<?php

namespace App\Form;

use App\Entity\Livraison;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivraisonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_produit')
            ->add('artiste')
            ->add('addres')
            ->add('date_sort')
            ->add('user_name')
            ->add('id_commende')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livraison::class,
        ]);
    }
}

templates/livraison/_delete_form.html.twig
<form method="post" action="{{ path('app_livraison_delete', {'id': livraison.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livraison.id) }}">
    <button class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700
     focus:outline-none focus:shadow-outline-purple">Delete</button>
</form>

templates/livraison/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
    <div class = "block text-sm">

<span class="text-gray-700 dark:text-gray-400">
        {{form_label(form.user_name) }}</span>
        {{ form_widget(form.user_name, {'attr': {'class': 'w-full h-12 px-4 mb-2 text-lg text-gray-700 placeholder-gray-600 border rounded-lg focus:shadow-outline'}}) }}


        <span style="color: red">
            {{ form_errors(form.user_name) }}</span>


<br><span class="text-gray-700 dark:text-gray-400">
            {{ form_label(form.date_sort) }}</span>

        {{ form_widget(form.date_sort) }}
        <span style="color: red">
            {{ form_errors(form.date_sort) }}</span><br>
        <span class="text-gray-700 dark:text-gray-400">
            {{ form_label(form.name_produit) }}</span>
        {{ form_widget(form.name_produit, {'attr': {'class': 'w-full h-12 px-4 mb-2 text-lg text-gray-700 placeholder-gray-600 border rounded-lg focus:shadow-outline'}}) }}
        <span style="color: red">
            {{ form_errors(form.name_produit) }}</span><br>
        <span class="text-gray-700 dark:text-gray-400">
            {{ form_label(form.id_commende) }}</span>
        {{ form_widget(form.id_commende) }}
        <span style="color: red">
            {{ form_errors(form.id_commende) }}</span><br>
        <span class="text-gray-700 dark:text-gray-400">
            {{ form_label(form.artiste) }}</span>
        {{ form_widget(form.artiste, {'attr': {'class': 'w-full h-12 px-4 mb-2 text-lg text-gray-700 placeholder-gray-600 border rounded-lg focus:shadow-outline'}}) }}
        <span style="color: red">
            {{ form_errors(form.artiste) }}</span><br>
        <span class="text-gray-700 dark:text-gray-400">
            {{ form_label(form.addres) }}</span>
        {{ form_widget(form.addres, {'attr': {'class': 'w-full h-12 px-4 mb-2 text-lg text-gray-700 placeholder-gray-600 border rounded-lg focus:shadow-outline'}}, {'attr': {'class': 'w-full h-12 px-4 mb-2 text-lg text-gray-700 placeholder-gray-600 border rounded-lg focus:shadow-outline'}}) }}
        <span style="color: red">
        {{ form_errors(form.addres) }}</span><br>















</div>

    <button class=" px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
    >{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/livraison/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livraison{% endblock %}

{% block body %}
    <h1>Edit Livraison</h1>

    {{ include('livraison/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700
     focus:outline-none focus:shadow-outline-purple" href="{{ path('app_livraison_index') }}">back to list</a>

    {{ include('livraison/_delete_form.html.twig') }}
{% endblock %}

templates/livraison/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livraison {% endblock %}

{% block body %}


    <table class="w-full whitespace-no-wrap">
        <thead>
            <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase
            border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                <th>Id</th>
                <th>Name_produit</th>
                <th>Artiste</th>
                <th>Addres</th>
                <th>Date_sort</th>
                <th>User_name</th>
                <th>commende Name</th>
                <th>actions</th>
            </tr>
        </thead>

        <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
        {% for livraison in livraisons %}
            <tr class="text-gray-700 dark:text-gray-400">
                <td>{{ livraison.id }}</td>
                <td>{{ livraison.nameProduit }}</td>
                <td>{{ livraison.artiste }}</td>
                <td>{{ livraison.addres }}</td>
                <td>{{ livraison.dateSort ? livraison.dateSort|date('Y-m-d') : '' }}</td>
                <td>{{ livraison.userName }}</td>
                <td>{{ livraison.idCommende }}</td>
                <td>
                    <a
                            href="{{ path('app_livraison_edit', {'id': livraison.id}) }}"
                    ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                        </svg>
                    </a>
                    <a href="{{ path('app_livraison_show', {'id': livraison.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-binoculars" viewBox="0 0 16 16">
                            <path d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z"/>
                        </svg></a>

                    <a href="{{ path('shift_row1', {'id': livraison.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-bar-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M6 8a.5.5 0 0 0 .5.5h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L12.293 7.5H6.5A.5.5 0 0 0 6 8Zm-2.5 7a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5Z"/>
                        </svg></a>
                    <a
                            href="{{ path('shift_row3', {'id': livraison.id}) }}"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-bar-left" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5ZM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5Z"/>
                        </svg>
                    </a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <br>
    <a href="{{ path('app_livraison_new') }}"class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
    >Create new</a>


{% endblock %}

templates/livraison/new.html.twig
{% extends 'base.html.twig' %}


{% block title %}New Livraison{% endblock %}

{% block body %}


    {{ include('livraison/_form.html.twig') }}
<br><br>
    <a href="{{ path('app_livraison_index') }}" class="px-4 py-2 text-sm font-medium leading-5
    text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active
    :bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">back to list</a>
{% endblock %}

templates/livraison/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livraison{% endblock %}

{% block body %}


    <table class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ livraison.id }}</td>
            </tr>
            <tr>
                <th>Name_produit</th>
                <td>{{ livraison.nameProduit }}</td>
            </tr>
            <tr>
                <th>Artiste</th>
                <td>{{ livraison.artiste }}</td>
            </tr>
            <tr>
                <th>Addres</th>
                <td>{{ livraison.addres }}</td>
            </tr>
            <tr>
                <th>Date_sort</th>
                <td>{{ livraison.dateSort ? livraison.dateSort|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>User_name</th>
                <td>{{ livraison.userName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_livraison_index') }}"class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg
    active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">back to list</a>

    <a href="{{ path('app_livraison_edit', {'id': livraison.id}) }}"class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg
     active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">edit</a>

    {{ include('livraison/_delete_form.html.twig') }}
{% endblock %}