src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("commande")]
    private ?int $id = null;

    #[ORM\Column]
    #[Groups("commande")]
    private ?int $id_panier = null;

    #[ORM\Column(length: 255)]
    #[Groups("commande")]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    #[Groups("commande")]
    private ?string $nom = null;

    #[ORM\Column]
    #[Groups("commande")]
    private ?string $numero = null;

    #[ORM\Column(length: 255)]
    #[Groups("commande")]
    private ?string $status = null;

    #[ORM\Column]
    #[Groups("commande")]
    private ?int $total_amount = null;

    #[ORM\Column]
    #[Groups("commande")]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    #[Groups("commande")]
    private ?int $codepostal = null;

    #[ORM\Column(length: 255)]
    #[Groups("commande")]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups("commande")]
    private ?string $Statu_liv = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdPanier(): ?int
    {
        return $this->id_panier;
    }

    public function setIdPanier(int $id_panier): self
    {
        $this->id_panier = $id_panier;

        return $this;
    }


    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getTotalAmount(): ?string
    {
        return $this->total_amount;
    }

    public function setTotalAmount(string $total_amount): self
    {
        $this->total_amount = $total_amount;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCodepostal(): ?int
    {
        return $this->codepostal;
    }

    public function setCodepostal(int $codepostal): self
    {
        $this->codepostal = $codepostal;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function __toString(): string
    {
       return $this->getNom();
    }

    public function getStatuLiv(): ?string
    {
        return $this->Statu_liv;
    }

    public function setStatuLiv(?string $Statu_liv): self
    {
        $this->Statu_liv = $Statu_liv;

        return $this;
    }

}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_panier')
            ->add('prenom')
            ->add('nom')
            ->add('numero')
            ->add('status')
            ->add('total_amount')
            ->add('created_at')
            ->add('codepostal')
            ->add('adresse')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700
     focus:outline-none focus:shadow-outline-purple">Delete</button>
</form>

templates/commande/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
<div class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700
focus:border-purple-400 focus:outline-none focus:shadow-outline-purple
 dark:text-gray-300 dark:focus:shadow-outline-gray form-input">
    {{ form_label(form) }}
    {{ form_widget(form )}}
    {{ form_errors(form, {'attr': {'class': 'text-xs text-red-600 dark:text-red-400'}}) }}

</div>
    <button class=" px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
    >{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700
    focus:outline-none focus:shadow-outline-purple" href="{{ path('app_commande_index') }}">back to list</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table >
        <thead>
            <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase
                border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                <th>Id</th>
                <th>Id_panier</th>
                <th>Prenom</th>
                <th>Nom</th>
                <th>Numero</th>
                <th>Status</th>
                <th>Total amount</th>
                <th>Created at</th>
                <th>Codepostal</th>
                <th>Adresse</th>
                <th>Statu Livraison</th>
                <th>actions</th>

            </tr>
        </thead>
        <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
        {% for commande in commandes %}
            <tr class="text-gray-700 dark:text-gray-400">
                <td>{{ commande.id }}</td>
                <td>{{ commande.idPanier }}</td>
                <td>{{ commande.prenom }}</td>
                <td>{{ commande.nom }}</td>
                <td>{{ commande.numero }}</td>
                <td>{{ commande.status }}</td>
                <td>{{ commande.totalAmount }}</td>
                <td>{{ commande.createdAt ? commande.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.codepostal }}</td>
                <td>{{ commande.adresse }}</td>
                <td>{{ commande.statuLiv }}</td>
                <td>
                    <a href="{{ path('app_commande_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>
                    <a href="{{ path('shift_row4',{'id': commande.id}) }}">Livrai</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commande_new') }}"class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
    >Create new</a>
{% endblock %}

templates/commande/index2.html.twig
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ashion Template">
    <meta name="keywords" content="Ashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/elegant-icons.css') }}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/jquery-ui.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/magnific-popup.css') }}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/owl.carousel.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/slicknav.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/style.css') }}" type="text/css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios@1.1.2/dist/axios.min.js"></script>



</head>

<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__close">+</div>
    <ul class="offcanvas__widget">
        <li><span class="icon_search search-switch"></span></li>
        <li><a href="#"><span class="icon_heart_alt"></span>
                <div class="tip">2</div>
            </a></li>
        <li><a href="#"><span class="icon_bag_alt"></span>
                <div class="tip">2</div>
            </a></li>
    </ul>
    <div class="offcanvas__logo">
        <a href="./base-front.html.twig"><img src="{{ asset('front/img/logo.png') }}" alt=""></a>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__auth">
        <a href="#">Login</a>
        <a href="#">Register</a>
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-3 col-lg-2">
                <div class="header__logo">
                    <a href="./base-front.html.twig"><img src="{{ asset('front/img/logo.png') }}" alt=""></a>
                </div>
            </div>
            <div class="col-xl-6 col-lg-7">
                <nav class="header__menu">
                    <ul>
                        <li class="active"><a href="./base-front.html.twig">Home</a></li>
                        <li><a href="#">Women’s</a></li>
                        <li><a href="#">Men’s</a></li>
                        <li><a href="./shop.html">Shop</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="dropdown">
                                <li><a href="./product-details.html">Product Details</a></li>
                                <li><a href="/lignepanier">Shop Cart</a></li>
                                <li><a href="../commande">Checkout</a></li>
                                <li><a href="./blog-details.html">Blog Details</a></li>
                            </ul>
                        </li>
                        <li><a href="./blog.html">Blog</a></li>
                        <li><a href="./contact.html">Contact</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                <div class="header__right">
                    <div class="header__right__auth">
                        <a href="#">Login</a>
                        <a href="#">Register</a>
                    </div>
                    <ul class="header__right__widget">
                        <li><span class="icon_search search-switch"></span></li>
                        <li><a href="#"><span class="icon_heart_alt"></span>
                                <div class="tip">2</div>
                            </a></li>
                        <li><a href="../lignepanier"><span class="icon_bag_alt"></span>
                                <div class="tip">2</div>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="canvas__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<!-- Header Section End -->

<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Shop Cart Section Begin -->
<section class="shop-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <table class="shop__cart__table">
                    <thead>
                    <tr>
                        <th  style="color: red" >Id</th>
                        <th style="color: red">panier</th>
                        <th style="color: red">Prenom</th>
                        <th style="color: red">Nom</th>
                        <th style="color: red">Numero</th>
                        <th style="color: red">Status</th>
                        <th style="color: red">Total</th>
                        <th style="color: red">Date</th>
                        <th style="color: red">Codepostal</th>
                        <th style="color: red">Adresse</th>
                        <th style="color: red">Statu </th>
                        <th style="color: red">actions</th>

                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    {% for commande in commandes1 %}
                        <tr >
                            <td >{{ commande.id }}</td>
                            <td>{{ commande.idPanier }}</td>
                            <td>{{ commande.prenom }}</td>
                            <td>{{ commande.nom }}</td>
                            <td>{{ commande.numero }}</td>
                            <td>{{ commande.status }}</td>
                            <td>{{ commande.totalAmount }}</td>
                            <td>{{ commande.createdAt ? commande.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                            <td>{{ commande.codepostal }}</td>
                            <td>{{ commande.adresse }}</td>
                            <td>{{ commande.statuLiv }}</td>
                            <td>
                                <a href="{{ path('app_commande_show', {'id': commande.id}) }}">show</a>
                                <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>
                                <a href="{{ path('shift_row4',{'id': commande.id}) }}">Livrai</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="11">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">

            </div>

        </div>

            </div>







            </div>
        </div>
    </div>
</section>

<!-- Footer Section End -->

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('js/jquery-ui.min.js') }}js/jquery-ui.min.js"></script>
<script src="{{ asset('js/mixitup.min.js') }}"></script>
<script src="{{ asset('js/jquery.countdown.min.js') }}"></script>
<script src="{{ asset('js/jquery.slicknav.js') }}"></script>
<script src="{{ asset('js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('js/jquery.nicescroll.min.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>
</body>

</html>

templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande/_form.html.twig') }}

    <a href="{{ path('app_commande_index') }}"class="px-4 py-2 text-sm font-medium leading-5
    text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active
    :bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">back to list</a>
{% endblock %}

templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Id_panier</th>
                <td>{{ commande.idPanier }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ commande.prenom }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ commande.nom }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ commande.numero }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ commande.status }}</td>
            </tr>
            <tr>
                <th>Total_amount</th>
                <td>{{ commande.totalAmount }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ commande.createdAt ? commande.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Codepostal</th>
                <td>{{ commande.codepostal }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ commande.adresse }}</td>
            </tr>
            <tr>
                <th>Staatu Livraison</th>
                <td>{{ commande.statuLiv}}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commande_index') }}"class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg
    active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">back to list</a>

    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}"class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg
     active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">edit</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}